### ISSUE TITLE
docs/user-guide | suggestions

### ISSUE THREAD

**Issue by nyaneet** [a-givertzman/sss#4]

**Comment by nyaneet** [comment]
To improve quality of our documentation, it is proposed to install the ["Russian - Code Spell Checker"](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-russian) extension for VS Code.

The configuration file `.vscode/settings.json` has been added in commit 817951c50e28a1e32fd8dfbf59be0fa3780c000f, which includes the necessary settings.

**Comment by nyaneet** [comment]
Some typos were fixed in commit 3fb02fd2454691c54a3d31f36e4728619f062540.

**Comment by nyaneet** [comment]
Proposal: Add Category Color Legend Table

It might be good to add separate table that lists all categories of cargo (tanks, stores, general cargo) with their corresponding color designations.

This table would serve as quick reference guide for users to understand the color coding used throughout the documentation.

**Comment by nyaneet** [comment]
The last sentence in the [line](https://github.com/a-givertzman/sss/blob/36a70d9ff809b628039769494fdf212a11734233/docs/user-guide/ru/part03_loading/%D1%81hapter04_bulkCargo/chapter04_bulkCargo.md?plain=1#L3C160-L3C172) breaks off

**Comment by Mr-Ivn** [comment]
Added [list of restrictions](https://github.com/a-givertzman/sss/blob/c44f4865fba090c11076b62eca1d657043a5d59d/docs/user-guide/ru/part03_loading/chapter03_stores/chapter03_stores.md?plain=1#L27) for stores
